version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: vault-db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: vault-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/vault
      - SECRET_KEY=cambiame-por-algo-seguro
      - USE_DOTENV=0
    restart: unless-stopped

volumes:
  postgres_data: