#!/usr/bin/env bash

set -euo pipefail

FORCE=0
if [[ "${1-}" == "--force" ]]; then
  FORCE=1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"

if [[ -f "$ENV_FILE" && $FORCE -ne 1 ]]; then
  echo ".env already exists at $ENV_FILE. Use --force to overwrite."
  exit 0
fi

echo "Generating .env at $ENV_FILE"

umask 077

SECRET_KEY=$(openssl rand -hex 32 2>/dev/null || python - <<'PY'
import os,sys
print(os.urandom(32).hex())
PY
)

cat > "$ENV_FILE" <<EOF
# Local .env generated by scripts/init_env.sh
SECRET_KEY=${SECRET_KEY}
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Local SQLite DB in project root to keep it simple for local dev
DATABASE_URL=sqlite:///./vault.db
DATABASE_KEY=

# For local dev allow all origins (safe for development). In production set this.
CORS_ORIGINS=

# Optional redis for rate-limiter (leave empty for in-memory)
REDIS_URL=

# Port for uvicorn
PORT=8000
EOF

echo ".env created. Keep it secret and do not commit it."
echo "Run: source .env (or the app will load it via python-dotenv automatically)"

# Ensure explicit restrictive permissions in case umask was changed
chmod 600 "$ENV_FILE" || true

exit 0
